authforms/authforms/urls.py
from django.contrib import admin
from django.urls import path, include


app_name = "authforms"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authforms_app.urls")),
    path('users/', include("users.urls")),

]

authforms/authforms_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'authforms_app'

urlpatterns = [
    path('', views.frontpage, name="frontpage"),
]

authforms/authforms_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authforms.urls")),
    path('users/', include("users.urls")),

]

authforms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authform.urls")),
    path('users/', include("users.urls")),

]

authforms/users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('profile/', views.profile, name="profile"),

]

authforms/authforms_app/models.py
from django.db import models

# Create your models here.

authforms/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    api_key = models.TextField(max_length=32, blank=True)
    topic = models.TextField(max_length=32, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

authforms/authforms_app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import requests

# Create your views here.

@login_required(login_url='/users/login/')
def frontpage(request):
    context = {}
    user = request.user
    api_key = user.profile.api_key
    topic = user.profile.topic.lower()

    url= f"https://api.nytimes.com/svc/topstories/v2/{topic}.json?api-key={api_key}"
    res = requests.get(url).json()
    if "fault" not in res.keys():
        context["results"] = res["results"]

    return render(request, "frontpage.html", context)

authforms/users/views.py
from django.shortcuts import render
from django.contrib.auth import logout as django_logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required



# Create your views here.
@login_required(login_url='/users/login/')
def logout(request):
    django_logout(request)
    return HttpResponseRedirect(reverse('users:login'))

def register(request):
    """Register a new user."""

    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()

    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

    if form.is_valid():
        new_user = form.save()
        # Log the user in and then redirect to home page.
        authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
        login(request, authenticated_user)
        return HttpResponseRedirect(reverse('authforms_app:frontpage'))
    context = {'form': form}
    return render(request, 'register.html', context)

@login_required(login_url='/users/login/')
def profile(request):
    context = {}
    user = request.user
    context["user"] = user
    if "API-key" in request.POST:
        user.profile.api_key = request.POST["API-key"]
        user.save()

    if "topic" in request.POST:
        user.profile.topic = request.POST["topic"]
        user.save()

    return render(request, "profile.html", context)

authforms/authforms/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <div class="container">

    <nav class="navbar navbar-dark bg-dark navbar-expand-lg" style="background-color: #e3f2fd;">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">

            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="navbar-brand" href="#">Hello, {{ user.username }}.<a/>
            </li>

            <li class="nav-item">
                <a class="nav-link " href="{% url 'authforms:frontpage' %}">Front page </a>
            </li>

            <li class="nav-item">
                <a class="nav-link " href="{% url 'users:profile' %}">Profile </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}"> Log out</a>
            </li>
            {% else %}
             <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
             </li>
            {% endif %}

        </ul>
      </div>
    </nav>
 </div>

 <div class="container">
    <h3>AuthForms</h3>
    {% block content %}

    {% endblock %}
 </div>
</body>
</html>

authforms/authforms_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <div class="container">

    <nav class="navbar navbar-dark bg-dark navbar-expand-lg" style="background-color: #e3f2fd;">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">

            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="navbar-brand" href="#">Hello, {{ user.username }}.<a/>
            </li>

            <li class="nav-item">
                <a class="nav-link " href="{% url 'authforms_app:frontpage' %}">Front page </a>
            </li>

            <li class="nav-item">
                <a class="nav-link " href="{% url 'users:profile' %}">Profile </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}"> Log out</a>
            </li>
            {% else %}
             <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
             </li>
            {% endif %}

        </ul>
      </div>
    </nav>
 </div>

 <div class="container">
    <h3>AuthForms</h3>
    {% block content %}

    {% endblock %}
 </div>
</body>
</html>

authforms/authforms_app/templates/frontpage.html
{% extends "base.html" %}

{% block content %}

<h1>Home Page</h1>

{% for article in results %}

<a href="{{article.url}}">{{article.title}}</a>
<p>{{article.abstract}}</p>


{% endfor %}


{% endblock %}

authforms/authforms_app/templates/news.html
{% extends "base.html" %}

{% block content %}




{% endblock %}

authforms/users/templates/login.html
{% extends "base.html" %}

{% block content %}
    <br>
    <div class="mx-auto">
        {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
        {% endif %}

        <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">log in</button>
            <input type="hidden" name="next" value="{% url 'authforms_app:frontpage' %}" />
        </form>

        No account yet?<a href="{% url 'users:register' %}"> Register here.</a>
    </div>
{% endblock %}

authforms/users/templates/profile.html
{% extends "base.html" %}

{% block content %}

<table class="table">
  <tbody>
  <tr>
      <td scope="col">User name:</td>
      <td>{{user.username}}</td>
  </tr>

  <tr>
      <td scope="col">First name:</td>
      <td>{{user.first_name}}</td>
  </tr>

  <tr>
      <td scope="col">Last name:</td>
      <td>{{user.last_name}}</td>
  </tr>

  <tr>
      <td scope="col">E-mail:</td>
      <td>{{user.email}}</td>
  </tr>

  <tr>
      <form action="{% url 'users:profile' %}" method="post">
          {% csrf_token %}
          <td scope="col">API-key:</td>
          <td><input type="password" name="API-key" value="{{user.profile.api_key}}"><input type="submit" value="Submit"></td>
      </form>
  </tr>

    <tr>
      <form action="{% url 'users:profile' %}" method="post">
          {% csrf_token %}
          <td scope="col">Topic of preference:</td>
          <td><input type="text" name="topic" value="{{user.profile.topic}}"><input type="submit" value="Submit"></td>
      </form>
  </tr>


  </tbody>
</table>




{% endblock %}

authforms/users/templates/register.html
{% extends "base.html" %}

{% block content %}
    <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'authforms_app:frontpage' %}" />
    </form>
{% endblock content %}